export const CATEGORIES = [
  { value: 'hipbelts', label: 'Hipbelts' },
  { value: 'long-harams', label: 'Long Harams' },
  { value: 'combo-sets', label: 'Combo Sets' },
  { value: 'sarees', label: 'Sarees' },
  { value: 'dresses', label: 'Dresses' },
  { value: 'short-necklaces', label: 'Short Necklaces' },
  { value: 'jumkas', label: 'Jumkas' },
  { value: 'buttalu', label: 'Buttalu' },
  { value: 'chandra-haralu', label: 'Chandra Haralu' },
  { value: 'black-beads', label: 'Black Beads' },
  { value: 'bangles', label: 'Bangles' },
  { value: 'rings', label: 'Rings' },
  { value: 'necklaces', label: 'Necklaces' },
  { value: 'bracelets', label: 'Bracelets' },
  { value: 'earrings', label: 'Earrings' },
  { value: 'pendants', label: 'Pendants' },
];
